apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hmhcluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-035038a0232552bfd }
      us-east-1b: { id: subnet-0e26689cd8791c364 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t3.small
    desiredCapacity: 1
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true