apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmhdemo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hmhdemo
  template:
    metadata:
      labels:
        app: hmhdemo
    spec:
      containers:
        - name: hmhdemo
          image: 239465880452.dkr.ecr.us-east-1.amazonaws.com/hmh-project/tutorial
          ports:
            - containerPort: 8080